# Exceptions-String_to_Integer

Another problem with exception.

First I tried to solve this problem with 'atoi', but 'atoi' has no-throw guarantee: this function never throws exceptions.
Therefore I used stoi function.
